### ISSUE TITLE
Pro Micro ATmega32U4

### ISSUE THREAD

**Issue by ElCrackFPS** [Synless/Keyboard#1]
I am doing a very similar project even though I made it work, I am interested in the mapping function, I have little knowledge about programming, my doubt is it can be compatible with pro micro

**Comment by Synless** [comment]
You can assume that it can be compatible with a Pro Micro, the Atmel 32U4 is a very widespread MCU. Could you elaborate on what you need info on ? Mapping in terms of matrix mapping or maybe the saving/modification of the profile over serial ?

**Comment by ElCrackFPS** [comment]
Hello!
I try to use your kerboard.ino code that you offer to keep everything in a single pro micro, but I don't understand how SynlessKeyboardMapper works in the code.
The design I'm using is this https://imgur.com/a/JwhQ7tD

**Comment by Synless** [comment]
This piece of tool is a bit complicated and rather custom I have to admit. Since my coding skills are not the sharpest the design pattern and architecture of the program could be improved immensely I am sure.

The idea here is to pass the whole configuration/layout as a string to the serial port of the Arduino. The Arduino then splits the string and get the key mapped for each switch. I used `WriteKeyMod`, `StoreKeyMod` and `SendLayout` (commented on the latest revision of the Arduino code)  to set the config, store the config, and send the config through serial.

Note that the Atmel 32U4 does not work like the Atmel SAMD21 does when it comes to storing data. I am rusty on the topic but you will have no trouble finding that online.
If you wish to store and read configuration data and use this tool you will first have to see how to store data at runtime on a Arduino Pro Micro / Arduino Leonard (and any other 32u4 based board). Then you would have to change the layout of the keyboard for yours, check what the string looks like before sending over serial, follow the data.

**Comment by Synless** [comment]
Since I moved away from the SAMD21 to 2x32U4 and the project has changed a lot, I am refactoring this repo. I will be creating another repo with the old material and resources later on for this first revision.
